/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Fox(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/Fox.glb");
  const { actions } = useAnimations(animations, group);
  console.log(actions)  
  useEffect(() => {
    /*     console.log(actions) */
    actions.Run.play()
  }, [])

  return (
    
    <group ref={group} {...props} dispose={null}>
      <group scale={0.05}>
        <group name="root">
          <skinnedMesh
            name="fox"
            geometry={nodes.fox.geometry}
            material={materials.fox_material}
            skeleton={nodes.fox.skeleton}
          />
          <primitive object={nodes._rootJoint} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/Fox.glb");
