/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/Parrot.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    /*     console.log(actions) */
    actions.parrot_A_.play()
  }, [])

  /*   useEffect(() => {
    console.log(actions);
}, []); */

  /*   useEffect(() => {
  actions?.jump.play()
})  */
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene" scale={0.03} position={[0, 2, 0]}>
        <mesh
          name="mesh_0"
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
          morphTargetDictionary={nodes.mesh_0.morphTargetDictionary}
          morphTargetInfluences={nodes.mesh_0.morphTargetInfluences}
          /* onClick={(e) => console.log('click')} */
          /*           onClick={(e) => actions.jump.play()}  */
        />
        {/* <mesh onClick={(e) => actions.jump.play()} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('./models/Parrot.glb')
