/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/Parrot.glb -o src/modelComponents/Parrot.jsx -r 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Parrot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/Parrot.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} morphTargetDictionary={nodes.mesh_0.morphTargetDictionary} morphTargetInfluences={nodes.mesh_0.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Parrot.glb')
